### ISSUE TITLE
Model training scripts code

### ISSUE THREAD

**Issue by kibergus** [makegirlsmoe/makegirlsmoe_web#35]
Hi. I liked MakeGirlsMoe demo very much, thank you for great work. Repo description states that you decided to open-source model training scripts after the release of Chainer 3.0. Looks like it has been released (https://groups.google.com/forum/#!topic/chainer/Raw_ms3jHcs). Do you still have plans to open-source training scripts?
Thanks.

**Comment by Aixile** [comment]
The new version of MakeGirlsMoe will be presented at Comic Market 93.
I will release the code after that with the latest version.

**Comment by TetsuFe** [comment]
Do you still have plans to open-source training scripts? I don't wait! 笑

**Comment by Aixile** [comment]
@TetsuFe 
Hi, after some consideration, we decide not to open source our training scripts. The reason is our training scripts are closely combined with our dataset, however, we cannot provide the training dataset because of copyright considerations.
I think many open-sourced GAN implements can also give great results, might better than our released model. ( For example, the progressive gan implement [here](https://github.com/pfnet-research/chainer-gan-lib), stack-gan-v2 model [here](https://github.com/hanzhanggit/StackGAN-v2)) You should try them.
